### ISSUE TITLE
missing argument when calling triton_coor_descent

### ISSUE THREAD

**Issue by wangzizhao** [lucidrains/CoLT5-attention#9]
Thanks for the great code! 

However, when I run the test snippet in this [issue](https://github.com/lucidrains/CoLT5-attention/issues/8), I got the following error
```
Traceback (most recent call last):
  File "perf_test.py", line 14, in <module>
    result2 = triton_coor_descent(s, n_iters=50, k=64, eps=1.0, checkpoint_segments=1)
  File "/home/zwang/miniconda3/envs/mtr/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/zwang/miniconda3/envs/mtr/lib/python3.8/site-packages/colt5_attention/triton_coor_descent.py", line 501, in triton_coor_descent
    return _coor_descent.apply(s, n_iters, k, eps, eps_init, eps_decay, mask, checkpoint_segments)
  File "/home/zwang/miniconda3/envs/mtr/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 102, in decorate_fwd
    return fwd(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'checkpoint_segments'
```

Maybe in this [line](https://github.com/lucidrains/CoLT5-attention/blob/07f55a3091e84f8bbe738f7510e6741bc770239d/colt5_attention/triton_coor_descent.py#L315), `self` should be removed after adding `@staticmethod`? The same may apply to `backward()` as well.

**Comment by lucidrains** [comment]
@wangzizhao are you a researcher looking into coordinate descent routing? has there been any new developments?

**Comment by wangzizhao** [comment]
Thanks for confirming so fast! Unfortunately, I am trying to apply this great topK tool to other domains and not aware of any recent progress.
